spring.data.mongodb.uri=mongodb+srv://roshansaif764_db_user:IhLfaaQ8zs2PbGTC@cluster0.szvdfiz.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = journaldb
spring.data.mongodb.auto-index-creation=true